### ISSUE TITLE
Can the test result be a video?

### ISSUE THREAD

**Issue by c1a1o1** [vskadandale/vocalist#4]
Can the test result be a video?

**Comment by vskadandale** [comment]
Your question doesn't make sense. The result is accuracy. In case you want to know if the model can be tested on a video, you need to process the video in the same way you process LRS2 dataset as done in Wav2Lip paper. The code to test directly on a video is not available as such in this repository. However, it is very straightforward to do that if you follow the preprocessing steps from Wav2Lip paper.
