### ISSUE TITLE
Why is the test result not an image or video?

### ISSUE THREAD

**Issue by c1a1o1** [vskadandale/vocalist#6]
Thanks for sharing your groundbreaking research. Why is the test result not an image or a video?

D:\anaconda\python.exe D:/work/vgan/vocalist-main/t1est_lrs2.py
use_cuda: True
total trainable params 80106561
K5:0.1553,K7:0.1748,K9:0.1553,K11:0.1553,K13:0.1650,K15:0.1553: : 1it [00:15, 15.05s/it]

Process finished with exit code 0

**Comment by ka106** [comment]
Hi,can you tell me how did you solve this problem? #2 .I encountered the same error when I run test_acappella.py,but I have preprocessed the dataset.
